application: auto-sheriff
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: nannybot.html
  upload: nannybot.html
- url: /closers
  static_files: closers.html
  upload: closers.html
- url: /flakes
  static_files: flakes.html
  upload: flakes.html
- url: /flake_data
  static_files: flakes.json
  upload: flakes.json
- url: /components
  static_dir: bower_components
- url: /scripts
  static_dir: scripts
- url: /ui
  static_dir: ui
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /.*
  script: main.app


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.sqlite$
- ^(.*/)?LICENSE$
- ^(.*/)?README$
- ^(.*/)?Makefile$
